# Generated by Django 5.1.6 on 2025-10-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0016_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='product',
            name='unique_sku_not_deleted',
        ),
    ]
