# Generated by Django 5.1.6 on 2025-10-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0018_category_display_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_number',
        ),
    ]
