# Generated by Django 5.1.6 on 2025-10-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0022_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='landmark',
            field=models.CharField(blank=True, help_text='Nearby landmark for easy location', max_length=255, null=True),
        ),
    ]
