# Generated by Django 5.1.6 on 2026-01-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0036_order_refund_amount_order_refund_processed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='wallet',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='Wallet',
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
