# Generated by Django 5.1.6 on 2026-01-22 11:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0040_order_return_approved_at_order_return_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='wallet_amount_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Amount paid from wallet'),
        ),
    ]
