# Generated by Django 5.1.6 on 2026-03-03 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0047_fix_offer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
