# Generated by Django 5.1.6 on 2026-03-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0048_offerapplication_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerapplication',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Offer Application', 'verbose_name_plural': 'Offer Applications'},
        ),
        migrations.RemoveField(
            model_name='offerapplication',
            name='created_at',
        ),
    ]
