# Generated by Django 5.1.6 on 2026-03-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0052_order_return_rejected_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'created_at')},
        ),
    ]
