# Generated by Django 5.1.6 on 2026-03-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0054_orderitem_return_approved_at_orderitem_return_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='apply_to_all_variants',
            field=models.BooleanField(default=True, help_text='Apply discount to all variants of the product'),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='apply_to_all_variants',
            field=models.BooleanField(default=True, help_text='Apply discount to all variants of the product'),
        ),
    ]
