# Generated by Django 5.1.6 on 2026-03-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0055_categoryoffer_apply_to_all_variants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='apply_to_all_variants',
        ),
    ]
