# Generated by Django 5.1.6 on 2026-03-10 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0057_categoryoffer_apply_to_all_variants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='apply_to_all_variants',
        ),
    ]
