# Generated by Django 5.2.5 on 2026-04-04 07:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0059_offerapplication_applied_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, underscore allowed.', regex='^[a-zA-Z0-9_]+$')]),
        ),
    ]
