# Generated by Django 5.1.6 on 2026-04-07 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0061_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonalDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g., 20 for 20%)', max_digits=5)),
                ('discount_fixed', models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount in ₹', max_digits=10)),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required', max_digits=10)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage offers)', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('usage_limit', models.IntegerField(default=0, help_text='0 = unlimited')),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seasonal Discount',
                'verbose_name_plural': 'Seasonal Discounts',
            },
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='offer_type',
            field=models.CharField(choices=[('product', 'Product Offer'), ('category', 'Category Offer'), ('seasonal', 'Seasonal Discount')], max_length=20),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='seasonal_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='sanjeri_app.seasonaldiscount'),
        ),
    ]
