# Generated by Django 5.1.6 on 2026-04-07 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0064_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_requested_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
