# Generated by Django 5.1.6 on 2025-10-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0015_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_name_not_deleted',
        ),
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_category_slug_not_deleted',
        ),
    ]
