# Generated by Django 5.1.6 on 2025-10-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0017_remove_product_unique_sku_not_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
