# Generated by Django 5.1.6 on 2025-10-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0020_remove_product_discount_price_remove_product_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile.png', null=True, upload_to='profile_images/'),
        ),
    ]
