# Generated by Django 5.1.6 on 2025-10-30 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0024_cart_wishlist_wishlistitem_wishlist_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
