# Generated by Django 5.1.6 on 2026-02-28 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0042_order_offer_discount_categoryoffer_productoffer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offerapplication',
            options={'verbose_name': 'Offer Application', 'verbose_name_plural': 'Offer Applications'},
        ),
    ]
