# Generated by Django 5.1.6 on 2026-03-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0045_categoryoffer_discount_value_categoryoffer_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoffer',
            name='product',
        ),
        migrations.AddField(
            model_name='productoffer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='offers', to='sanjeri_app.product'),
        ),
    ]
