# Generated by Django 5.1.6 on 2026-03-01 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0046_remove_productoffer_product_productoffer_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoffer',
            options={'verbose_name': 'Category Offer', 'verbose_name_plural': 'Category Offers'},
        ),
        migrations.AlterModelOptions(
            name='offerapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'Offer Application', 'verbose_name_plural': 'Offer Applications'},
        ),
        migrations.AlterModelOptions(
            name='productoffer',
            options={'verbose_name': 'Product Offer', 'verbose_name_plural': 'Product Offers'},
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='min_cart_value',
        ),
        migrations.RemoveField(
            model_name='categoryoffer',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='active',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='max_discount_amount',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='min_cart_value',
        ),
        migrations.RemoveField(
            model_name='productoffer',
            name='offer_type',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='discount_fixed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount in ₹', max_digits=10),
        ),
        migrations.AddField(
            model_name='offerapplication',
            name='offer_name',
            field=models.CharField(blank=True, help_text='Snapshot of offer name at time of application', max_length=200),
        ),
        migrations.AddField(
            model_name='productoffer',
            name='discount_fixed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed amount discount in ₹', max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_offers', to='sanjeri_app.category'),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g., 20 for 20%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage offers)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='usage_limit',
            field=models.IntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='category_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='sanjeri_app.categoryoffer'),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_applications', to='sanjeri_app.orderitem'),
        ),
        migrations.AlterField(
            model_name='offerapplication',
            name='product_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='sanjeri_app.productoffer'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (e.g., 20 for 20%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (for percentage offers)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount required', max_digits=10),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='product_offers', to='sanjeri_app.product'),
        ),
        migrations.AlterField(
            model_name='productoffer',
            name='usage_limit',
            field=models.IntegerField(default=0, help_text='0 = unlimited'),
        ),
    ]
