# Generated by Django 5.1.6 on 2026-03-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0050_sync_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerapplication',
            name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='return_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
