# Generated by Django 5.1.6 on 2026-03-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0051_remove_offerapplication_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
