# Generated by Django 5.1.6 on 2026-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0056_fix_offer_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='apply_to_all_variants',
            field=models.BooleanField(default=False),
        ),
    ]
