# Generated by Django 5.1.6 on 2026-03-25 04:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanjeri_app', '0058_remove_categoryoffer_apply_to_all_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 25, 10, 29, 20, 406383)),
            preserve_default=False,
        ),
    ]
