import os
import django

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'sanjeri_project.settings')
django.setup()

from django.db import connection

queries = [
    """CREATE TABLE "sanjeri_app_referraloffer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "referrer_reward_type" varchar(10) NOT NULL, "referrer_reward_value" numeric(10, 2) NOT NULL, "referee_reward_type" varchar(10) NOT NULL, "referee_reward_value" numeric(10, 2) NOT NULL, "coupon_validity_days" integer NOT NULL CHECK ("coupon_validity_days" >= 0), "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);""",
    """ALTER TABLE "sanjeri_app_coupon" ADD COLUMN "user_id" bigint NULL CONSTRAINT "sanjeri_app_coupon_user_id_fk_sanjeri_a" REFERENCES "sanjeri_app_customuser"("id") DEFERRABLE INITIALLY DEFERRED;""",
    """CREATE INDEX "sanjeri_app_coupon_user_id_index" ON "sanjeri_app_coupon" ("user_id");"""
]

with connection.cursor() as cursor:
    for q in queries:
        try:
            cursor.execute(q)
            print("Successfully ran:", q[:50], "...")
        except Exception as e:
            print("Failed to run:", q[:50], "...")
            print("Error:", e)
